//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.30 at 09:14:47 PM EST 
//

package com.ibus.tmdb.client.domain;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Embedded;
import javax.persistence.Id;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Movie")
public class Movie 
{
	@Id
	private Long appengineId;
	
	//@XmlTransient
	/*@Parent 
	private com.googlecode.objectify.Key<MediaFile> parent;*/
	
    protected String score;
    protected String popularity;
    protected String name;
    @XmlElement(name = "alternative_name", required = true)
    protected String alternativeName;
    protected String type;
    @XmlElement(name = "id", required = true)
	private String tmdbId;
    @XmlElement(name = "imdb_id", required = true)
    protected String imdbId;
    protected String url;
    protected String overview;
    protected String rating;
    protected String released;
    protected String translated;
    protected String adult;
    protected String language;
    @XmlElement(name = "original_name", required = true)
    protected String originalName;
    protected String runtime;
    protected String budget;
    protected String revenue;
    protected String homepage;
    protected String votes;
    protected String certification;
	protected String version;
    @XmlElement(name = "last_modified_at", required = true)
    protected String lastModifiedAt;
    protected String trailer;
   /* @XmlElement(required = true)
    protected List<Category> categories;
    @XmlElement(required = true)
    protected List<Studio> studios;
    @XmlElement(required = true)
    protected List<Country> countries;*/
    
    @Embedded
    @XmlElementWrapper(name="images")
    @XmlElement(name="image",required = true)
    protected List<Image> images = new ArrayList<Image>();
    
    /*@XmlElement(required = true)
    protected List<Actor> cast;*/
    
    public String getScore() {
        return score;
    }


    public void setScore(String value) {
        this.score = value;
    }


    public String getPopularity() {
        return popularity;
    }


    public void setPopularity(String value) {
        this.popularity = value;
    }


    public String getName() {
        return name;
    }


    public void setName(String value) {
        this.name = value;
    }

    public String getAlternativeName() {
        return alternativeName;
    }


    public void setAlternativeName(String value) {
        this.alternativeName = value;
    }

    public String getType() {
        return type;
    }

    public void setType(String value) {
        this.type = value;
    }

  
    public String getImdbId() {
        return imdbId;
    }

    public void setImdbId(String value) {
        this.imdbId = value;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String value) {
        this.url = value;
    }

    public String getOverview() {
        return overview;
    }


    public void setOverview(String value) {
        this.overview = value;
    }

    public String getRating() {
        return rating;
    }

    public void setRating(String value) {
        this.rating = value;
    }

    public String getReleased() {
        return released;
    }

    public void setReleased(String value) {
        this.released = value;
    }
     
     
    public String getTranslated() {
        return translated;
    }

    public void setTranslated(String value) {
        this.translated = value;
    }

 
    public String getAdult() {
        return adult;
    }

   
    public void setAdult(String value) {
        this.adult = value;
    }

   
    public String getLanguage() {
        return language;
    }

   
    public void setLanguage(String value) {
        this.language = value;
    }

   
    public String getOriginalName() {
        return originalName;
    }

    public void setOriginalName(String value) {
        this.originalName = value;
    }

    public String getRuntime() {
        return runtime;
    }

   
    public void setRuntime(String value) {
        this.runtime = value;
    }

   
    public String getBudget() {
        return budget;
    }

   
    public void setBudget(String value) {
        this.budget = value;
    }

    public String getRevenue() {
        return revenue;
    }

   
    public void setRevenue(String value) {
        this.revenue = value;
    }

  
    public String getHomepage() {
        return homepage;
    }

   
    public void setHomepage(String value) {
        this.homepage = value;
    }

   
    public String getVotes() {
        return votes;
    }

    
    public void setVotes(String value) {
        this.votes = value;
    }

   
    public String getCertification() {
        return certification;
    }

   
    public void setCertification(String value) {
        this.certification = value;
    }

   
    public String getVersion() {
        return version;
    }

 
    public void setVersion(String value) {
        this.version = value;
    }

    public String getLastModifiedAt() {
        return lastModifiedAt;
    }

  
    public void setLastModifiedAt(String value) {
        this.lastModifiedAt = value;
    }

   
    public String getTrailer() {
        return trailer;
    }

   
    public void setTrailer(String value) {
        this.trailer = value;
    }

   /* 
    *//**
     * Gets the value of the categories property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categories property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategories().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Category }
     * 
     * 
     *//*
    public List<Category> getCategories() {
        if (categories == null) {
            categories = new ArrayList<Category>();
        }
        return this.categories;
    }

    *//**
     * Gets the value of the studios property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the studios property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStudios().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Studio }
     * 
     * 
     *//*
    public List<Studio> getStudios() {
        if (studios == null) {
            studios = new ArrayList<Studio>();
        }
        return this.studios;
    }

    *//**
     * Gets the value of the countries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the countries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCountries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Country }
     * 
     * 
     *//*
    public List<Country> getCountries() {
        if (countries == null) {
            countries = new ArrayList<Country>();
        }
        return this.countries;
    }*/

    /**
     * Gets the value of the images property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the images property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Image }
     * 
     * 
     */
    public List<Image> getImages() {
        if (images == null) {
            images = new ArrayList<Image>();
        }
        return this.images;
    }

    public void setImages(List<Image> images) 
    {
        this.images = images;
    }
    

   /* *//**
     * Gets the value of the cast property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cast property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCast().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Actor }
     * 
     * 
     *//*
    public List<Actor> getCast() {
        if (cast == null) {
            cast = new ArrayList<Actor>();
        }
        return this.cast;
    }*/
    

	public Long getId() {
		return appengineId;
	}


	public void setId(Long dsId) {
		this.appengineId = dsId;
	}
    
	
	public Image getImage(ImageSize imageSize)
	{
		Image ret = null;
		
		for(Image img : this.images)
		{
			if(img.size.equals(imageSize.toString()))
			{
				ret = img;
			}
			
			//if(i.size.equals(imageSize.toString()))
		}
		
		return ret;
	}
	
	public String getReleaseYear()
	{
		SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
		String ret;
		
		Date date;
		try 
		{
			date = (Date)formatter.parse(getReleased());
			formatter.applyPattern("yyyy");
			ret = formatter.format(date);
		} 
		catch (ParseException e) 
		{
			//if we cannot parse the string just return the whole date?
			ret = getReleased();
		}  
		
		return ret;
		
	}


/*	public com.googlecode.objectify.Key<MediaFile> getParent() {
		return parent;
	}


	public void setParent(com.googlecode.objectify.Key<MediaFile> parent) {
		this.parent = parent;
	}*/


	public String getTmdbId() {
		return tmdbId;
	}


	public void setTmdbId(String tmdbId) {
		this.tmdbId = tmdbId;
	}


	
	
}



























